[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "cd app/server && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30
